### ISSUE TITLE
"Your device's iOS version is not supported at this time."

### ISSUE THREAD

**Issue by ace101boss** [master131/iFakeLocation#15]
Anybody have a fix for "Your device's iOS version is not supported at this time."? I am on 13.3 and have the correct developer images downloaded.

**Comment by bgktmxg** [comment]
Cant remember if it was 13.3 or 13.4 that it stopped working but basically it doesnt appear to support the latest ios and im not sure it can be fixed until the dev can get it up to date.

**Comment by master131** [comment]
Can you please try the latest version? I've just published a new update.

**Comment by ace101boss** [comment]
@master131 Unfortunately, I am on Mac OS. Will there be a package for Mac OS coming soon? I just tested on the current Mac OS build with the newly linked developer images and I still get the same issue. Perhaps a Mac OS build of your new update may solve my issue.

**Comment by master131** [comment]
I have attached a macOS version, can you try that and see if it works?

**Comment by ace101boss** [comment]
@master131 There are signs of life in the new version you posted. It now displays that it is downloading a zipfile of the developer images but the package closes out before the download ever completes. The package will quit at various completion percentages (53-89%), thus it never completes. It should be noted that while the package quits, safari is still open and the progress bar freezes. 

Doing the manual developer images next to the package and inside of the package have the same result.
