### ISSUE TITLE
your device' ios vesion is not suppoted at this time

### ISSUE THREAD

**Issue by WJDanBB** [master131/iFakeLocation#16]
ios 13.4.1
in windows
can you help me 
 thanks you

**Comment by bgktmxg** [comment]
Hasnt worked for the latest few version of ios

**Comment by WJDanBB** [comment]
thanks you😬😬😬



发自我的iPhone


------------------ Original ------------------

**Comment by master131** [comment]
Can you please try the latest version? I've just published a new update.

**Comment by bgktmxg** [comment]
Im still getting unable to mount developer image for both 13.3 and 13.5. Will continue testing

**Comment by WJDanBB** [comment]
unexpectedly，that you would reply，thank you very much，i will try later. 😬😬😬



发自我的iPhone


------------------ Original ------------------

**Comment by ymmf80** [comment]
looks like the same is happening after updating the iOS to 14.1.

**Comment by WJDanBB** [comment]
已收悉。谢谢~
